"""add tag to work

Revision ID: 64095c608dc6
Revises: cb43d0177798
Create Date: 2025-11-28 17:08:59.001583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '64095c608dc6'
down_revision: Union[str, None] = 'cb43d0177798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worklogentry', sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worklogentry', 'tag')
    # ### end Alembic commands ###
