"""fix

Revision ID: cb43d0177798
Revises: 46d4ebc4492c
Create Date: 2025-11-28 07:40:11.667628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb43d0177798'
down_revision: Union[str, None] = '46d4ebc4492c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.alter_column('worklogentry', 'hours',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_constraint(op.f('worklogentry_user_id_fkey'), 'worklogentry', type_='foreignkey')
    op.create_foreign_key(None, 'worklogentry', 'user', ['user_id'], ['id'])
    op.drop_column('worklogentry', 'updated_at')
    op.drop_column('worklogentry', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worklogentry', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('worklogentry', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'worklogentry', type_='foreignkey')
    op.create_foreign_key(op.f('worklogentry_user_id_fkey'), 'worklogentry', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('worklogentry', 'hours',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=False)
    op.add_column('user', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
